Repository Dimanaux/md-notes, pull requests merged in 2020-05, with the labels that each got.

#42 I18n
  app/controllers/application_controller.rb
  app/controllers/concerns/internationalization.rb
  app/decorators/user_decorator.rb
  app/sanitizers/user/parameter_sanitizer.rb
  app/views/application/_navigation.html.slim
  app/views/application/_navigation_main.html.slim
  app/views/application/_navigation_user.html.slim
  app/views/pages/home.html.slim
  app/views/users/confirmations/new.html.slim
  app/views/users/notes/_search.html.slim
  app/views/users/notes/edit.html.slim
  app/views/users/notes/index.html.slim
  app/views/users/notes/new.html.slim
  app/views/users/notes/show.html.slim
  app/views/users/registrations/edit.html.slim
  app/views/users/registrations/new.html.slim
  app/views/users/sessions/new.html.slim
  app/views/users/shared/_links.html.slim
  app/views/users/show.html.slim
  config/application.rb
  config/database.yml
  config/locales/action_policy/en.yml
  config/locales/action_policy/ru.yml
  config/locales/flash.en.yml
  config/locales/flash/en.yml
  config/locales/flash/ru.yml
  config/locales/models/note/en.yml
  config/locales/models/note/ru.yml
  config/locales/models/user/en.yml
  config/locales/models/user/ru.yml
  config/locales/ru.yml
  config/locales/simple_form/en.yml
  config/locales/simple_form/ru.yml
  config/locales/time/en.yml
  config/locales/time/ru.yml
  config/locales/views/application/en.yml
  config/locales/views/application/ru.yml
  config/locales/views/common/en.yml
  config/locales/views/common/ru.yml
  config/locales/views/en.yml
  config/locales/views/pagination/en.yml
  config/locales/views/pagination/ru.yml
  config/locales/views/ru.yml
  config/locales/views/users/en.yml
  config/locales/views/users/notes/en.yml
  config/locales/views/users/notes/ru.yml
  config/locales/views/users/ru.yml
  db/migrate/20200426164838_add_locale_to_users.rb
  db/schema.rb
  spec/features/user/note/create_spec.rb
  spec/features/user/note/update_spec.rb
Labels: enhancement

#9 Rating
  .rubocop.yml
  Gemfile
  app/assets/javascripts/rating.js
  app/controllers/api/v1/application_controller.rb
  app/controllers/api/v1/users/notes/ratings_controller.rb
  app/controllers/users/notes_controller.rb
  app/decorators/note_decorator.rb
  app/interactors/notes/rate.rb
  app/interactors/notes/ratings/destroy.rb
  app/interactors/notes/ratings/find.rb
  app/interactors/notes/ratings/save.rb
  app/interactors/notes/unrate.rb
  app/interactors/notes/update_rating.rb
  app/models/note.rb
  app/models/rating.rb
  app/models/user.rb
  app/policies/rating_policy.rb
  app/views/users/notes/_rating.html.slim
  app/views/users/notes/show.html.slim
  config/routes.rb
  db/migrate/20200319043254_create_ratings.rb
  db/migrate/20200325195536_add_average_rating_to_notes.rb
  db/schema.rb
  spec/decorators/note_decorator_spec.rb
  spec/factories/ratings.rb
  spec/features/user/note/create_spec.rb
  spec/interactors/notes/rate_spec.rb
  spec/interactors/notes/ratings/find_spec.rb
  spec/interactors/notes/unrate_spec.rb
  spec/models/note_spec.rb
  spec/models/rating_spec.rb
  spec/models/user_spec.rb
  spec/policies/rating_policy_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: enhancement

#53 Update rails to 5.2.4.3
  Gemfile
  Gemfile.lock
Labels: dependencies

#54 Fix db config
  config/database.yml
Labels: bug

#57 Pretty previews
  app/decorators/note_decorator.rb
  app/views/users/notes/index.html.slim
Labels: enhancement

#55 Non existing subdomain error
  app/controllers/users/base_controller.rb
  config/locales/flash/en.yml
  config/locales/flash/ru.yml
Labels: bug

#56 Pointer as a cursor when hover rating stars
  app/assets/stylesheets/components/all.scss
  app/assets/stylesheets/components/notes.scss
Labels: bug, enhancement
